#!/usr/bin/env bash

set -e

TRINO_SESSION='--session=iceberg.compression_codec=GZIP --session=delta.compression_codec=GZIP'

SQL_INSERT='INSERT INTO data VALUES (1, 0), (2, 0), (3, 0);'
SQL_DROP_TABLE='DROP TABLE IF EXISTS data;'
SQL_CREATE_TABLE='CREATE TABLE data (key INT, value INT);'
SQL_DROP_SCHEMA="DROP SCHEMA IF EXISTS dml CASCADE;"
SQL_CREATE_SCHEMA="CREATE SCHEMA IF NOT EXISTS dml WITH (location = 's3a://dml/');"

for VARIANT in iceberg_mor delta_no_deletion_vectors; do

    if [[ "$VARIANT" == 'iceberg_mor' ]]; then
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT=iceberg
    elif [[ "$VARIANT" == 'delta_no_deletion_vectors' ]]; then
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT=delta
    else
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT="$VARIANT"
    fi

    rm -rf "$OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR"

    # Setup
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_DROP_SCHEMA"
    mcli mb -p minio/dml
    mcli rb --force minio/dml
    mcli mb minio/dml
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_CREATE_SCHEMA"

    # CREATE
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/create"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # INSERTs
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='INSERT INTO data VALUES (4, 0), (5, 0), (6, 0)'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='INSERT INTO data VALUES (7, 0), (8, 0), (9, 0)'
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/insert"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # DELETEs
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='DELETE FROM data WHERE key = 1;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='DELETE FROM data WHERE key = 2;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='DELETE FROM data WHERE key = 3;'
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/delete"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # UPDATEs
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='UPDATE data SET value = 1 WHERE key = 1;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='UPDATE data SET value = 1 WHERE key = 2;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='UPDATE data SET value = 1 WHERE key = 3;'
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/update"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # Mixed
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='DELETE FROM data WHERE key = 1;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='DELETE FROM data WHERE key = 2;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='INSERT INTO data VALUES (4, 0), (5, 0), (6, 0)'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='UPDATE data SET value = 1 WHERE key = 4;'
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute='UPDATE data SET value = 1 WHERE key = 5;'
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/mixed"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # Cleanup
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_DROP_SCHEMA"
    mcli rb --force minio/dml

done
