#!/usr/bin/env bash

TRINO_SESSION='--session=hive.hive_storage_format=PARQUET --session=delta.compression_codec=GZIP --session=iceberg.compression_codec=GZIP'

SQL_INSERT='INSERT INTO data (key, value) VALUES (1, 0), (2, 0), (3, 0), (4, 0);'
SQL_DELETE='DELETE FROM data WHERE key = 1;'
SQL_UPDATE='UPDATE data SET value = 1 WHERE key = 2;'
SQL_DROP_TABLE='DROP TABLE IF EXISTS data;'
SQL_CREATE_TABLE='CREATE TABLE data (key INT, value INT);'
SQL_DROP_SCHEMA="DROP SCHEMA IF EXISTS dml CASCADE;"
SQL_CREATE_SCHEMA="CREATE SCHEMA IF NOT EXISTS dml WITH (location = 's3a://dml/');"

for VARIANT in iceberg_mor delta_no_deletion_vectors; do

    if [[ "$VARIANT" == 'iceberg_mor' ]]; then
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT=iceberg
    elif [[ "$VARIANT" == 'delta_no_deletion_vectors' ]]; then
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT=delta
    else
        OUTPUT_DIR="${VARIANT}/trino"
        FORMAT="$VARIANT"
    fi

    rm -rf "$OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR"

    # Setup
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_DROP_SCHEMA"
    mcli mb -p minio/dml
    mcli rb --force minio/dml
    mcli mb minio/dml
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_CREATE_SCHEMA"

    # CREATE
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/create"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # INSERT
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/insert"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # DELETE
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DELETE"
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/delete"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # UPDATE
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_CREATE_TABLE"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_INSERT"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_UPDATE"
    mcli cp -r "minio/dml/data/" "$OUTPUT_DIR/update"
    $TRINO_HOME/bin/trino --catalog="$FORMAT" --schema=dml $TRINO_SESSION --execute="$SQL_DROP_TABLE"

    # Cleanup
    $TRINO_HOME/bin/trino $TRINO_SESSION --catalog="$FORMAT" --execute="$SQL_DROP_SCHEMA"
    mcli rb --force minio/dml

done
